// Generated by `pnpm i18n sync` from the English catalog and baseline.json; never edited by hand.
// The keys the catalog gained since 5.0.0, the first release of this major. A dictionary of
// your own may leave each one out: until it carries the key, the chart reads it in English and
// reports it to `onMissing`. The next major's baseline makes every one of them required.
export const KEYS_ADDED_IN_MAJOR = [
  'chrome.autoScale',
  'chrome.autoScaleMark',
  'chrome.currencyAndUnit',
  'chrome.deletePane',
  'chrome.logScale',
  'chrome.logScaleMark',
  'chrome.paneButtons',
  'chrome.priceLevelMenu',
  'chrome.scaleAsk',
  'chrome.scaleBid',
  'chrome.scaleHigh',
  'chrome.scaleLow',
  'chrome.scaleModes',
  'command.marksRefresh',
] as const

export type KeyAddedInMajor = (typeof KEYS_ADDED_IN_MAJOR)[number]
