// The stylesheet as a consumer meets it: one CSS asset in the export map, generated by the build,
// and a bundle that injects nothing.
//
// The dist blocks are vacuous until a build has run, the same shape the packed-declaration fixture
// uses. Run `pnpm --filter quickcharts build` and they judge the real artifact.
import { describe, expect, it } from 'vitest'
import manifest from '../../package.json'
import { selectorsOf, THEME_ROOT_ATTRIBUTE } from '../../src/theme/css-contract'
import { builtArtifact } from './stylesheetSource'

const css = builtArtifact('quickcharts.css')
const bundle = builtArtifact('index.js')

describe('the stylesheet in the export map', () => {
  it('publishes one CSS entry, in the workspace map and in the published map', () => {
    expect(manifest.exports['./styles.css']).toBe('./dist/quickcharts.css')
    expect(manifest.publishConfig.exports['./styles.css']).toBe('./dist/quickcharts.css')
  })

  it('declares the stylesheet as the package side effect a bundler must keep', () => {
    expect(manifest.sideEffects).toContain('dist/quickcharts.css')
    expect(manifest.sideEffects).toContain('src/styles/components/*.css')
  })

  it('packs the built stylesheet, and generates it from the build', () => {
    expect(manifest.files).toContain('dist')
    expect(manifest.scripts['build:theme']).toBe('node scripts/build-theme.mjs')
    // The bundler clears dist as it runs, so the generator follows it rather than preceding it; the
    // feature manifest and the guest follow the theme generator, because both read what it wrote,
    // and the wire schema follows them because it writes into the same cleared dist. The notices
    // follow: they read the installed packages, not dist, and the tarball carries them. The candidate
    // pack comes last: it packs what every earlier step wrote.
    expect(manifest.scripts.postbuild).toBe(
      'node scripts/build-theme.mjs && node scripts/build-feature-manifest.mjs && node scripts/build-guest.mjs && node scripts/build-rest-openapi.mjs && node scripts/build-third-party-notices.mjs && node scripts/pack-candidate.mjs',
    )
  })
})

describe('the built artifacts', () => {
  it('writes a scoped stylesheet beside the bundle', () => {
    if (css === null) return
    expect(css.length).toBeGreaterThan(1000)
    expect(selectorsOf(css).filter((s) => !s.startsWith(`[${THEME_ROOT_ATTRIBUTE}`))).toEqual([])
  })

  it('carries the drawing recipes, concatenated after the structural file', () => {
    if (css === null) return
    expect(css).toContain('.qc-drawing-toolbar')
    expect(css).toContain('.qc-drawing-settings-bar')
    expect(css.indexOf('.qc-drawing-toolbar')).toBeGreaterThan(css.indexOf('.qc-chrome'))
  })

  it('injects no styles from JavaScript', () => {
    if (bundle === null) return
    expect(bundle).not.toMatch(/createElement\(\s*['"]style['"]/)
    expect(bundle).not.toMatch(/insertRule|adoptedStyleSheets|CSSStyleSheet/)
    expect(bundle).not.toMatch(/<style/)
  })
})
