// The API-surface pin — a lightweight stand-in for an api-extractor report: the package's public
// RUNTIME surface as { name: typeof }. A diff here is a SemVer event to decide consciously (a
// removal/rename is breaking → major; an addition → minor, then extend the pin) — never noise to
// appease. The ~90 tool classes ARE public API: a licensee restores drawings through toolRegistry
// and may construct/extend the classes directly, so an accidental drop of one must fail loudly
// here rather than in their bundle. Type-only exports are erased at runtime and are gated by the
// clean-room consumer (clean-room/ts-consumer, skipLibCheck: false) against the shipped .d.ts.
import { describe, expect, it } from 'vitest'
import * as api from '../src/index'

const SURFACE: Record<string, string> = {
  AbcdPattern: 'function',
  AnchoredVolumeProfile: 'function',
  AnchoredVwap: 'function',
  Arc: 'function',
  Arrow: 'function',
  ArrowMarkDown: 'function',
  ArrowMarkUp: 'function',
  ArrowMarker: 'function',
  BarsPattern: 'function',
  Brush: 'function',
  Callout: 'function',
  CapturedBarsDrawing: 'function',
  Circle: 'function',
  Comment: 'function',
  ContentCard: 'function',
  CrossLine: 'function',
  Curve: 'function',
  CyclicLines: 'function',
  CypherPattern: 'function',
  DEFAULT_OPTIONS: 'object',
  DEFAULT_STYLE: 'object',
  DEFAULT_VISIBILITY: 'object',
  DatePriceRange: 'function',
  DateRange: 'function',
  DisjointChannel: 'function',
  DoubleCurve: 'function',
  Drawing: 'function',
  DrawingManager: 'function',
  ElliottCorrection: 'function',
  ElliottDoubleCombo: 'function',
  ElliottImpulse: 'function',
  ElliottTriangle: 'function',
  ElliottTripleCombo: 'function',
  Ellipse: 'function',
  ExtendedLine: 'function',
  FibArcs: 'function',
  FibChannel: 'function',
  FibCircles: 'function',
  FibExtension: 'function',
  FibRetracement: 'function',
  FibSpeedFan: 'function',
  FibSpiral: 'function',
  FibTimeExtension: 'function',
  FibTimeZone: 'function',
  FibWedge: 'function',
  FixedRangeVolumeProfile: 'function',
  FlagMark: 'function',
  FlatTopBottom: 'function',
  Forecast: 'function',
  GannBox: 'function',
  GannFan: 'function',
  GannSquare: 'function',
  GannSquareFixed: 'function',
  GhostFeed: 'function',
  GlyphMark: 'function',
  HeadAndShoulders: 'function',
  Highlighter: 'function',
  HorizontalLine: 'function',
  HorizontalRay: 'function',
  IconMark: 'function',
  ImageNote: 'function',
  InfoLine: 'function',
  InsidePitchfork: 'function',
  LabeledPolyline: 'function',
  LongPosition: 'function',
  Measure: 'function',
  ModifiedSchiffPitchfork: 'function',
  Note: 'function',
  ParallelChannel: 'function',
  PathLine: 'function',
  Pin: 'function',
  Pitchfan: 'function',
  Pitchfork: 'function',
  Polyline: 'function',
  PriceLabel: 'function',
  PriceNote: 'function',
  PriceRange: 'function',
  Ray: 'function',
  Rectangle: 'function',
  RegressionTrend: 'function',
  RotatedRectangle: 'function',
  SchiffPitchfork: 'function',
  Sector: 'function',
  ShortPosition: 'function',
  Signpost: 'function',
  SineLine: 'function',
  StickerMark: 'function',
  TOOL_CATEGORIES: 'object',
  TableNote: 'function',
  TextLabel: 'function',
  ThreeDrivesPattern: 'function',
  TimeCycles: 'function',
  ToolRegistry: 'function',
  TrendAngle: 'function',
  TrendLine: 'function',
  Triangle: 'function',
  TrianglePattern: 'function',
  VerticalLine: 'function',
  XabcdPattern: 'function',
  alphaOf: 'function',
  angleOf: 'function',
  barsInRange: 'function',
  cachedImageBitmap: 'function',
  distanceToLine: 'function',
  distanceToSegment: 'function',
  extendSegment: 'function',
  fibLevelColor: 'function',
  linearRegression: 'function',
  magnetSnap: 'function',
  midpoint: 'function',
  normalizeVisibility: 'function',
  parseDrawingsStore: 'function',
  parseIntervalContext: 'function',
  primeImageBitmap: 'function',
  restoreDrawings: 'function',
  segmentTextAngle: 'function',
  serializeDrawingsStore: 'function',
  setGlyphImageSource: 'function',
  snapToBar: 'function',
  toolRegistry: 'object',
  viewportOf: 'function',
  // Additive (minor): the reference's quick per-interval visibility rules, 2026-08-22.
  visibilityPreset: 'function',
  visibleAt: 'function',
  volumeProfile: 'function',
  withAlpha: 'function',
}

describe('@trdrs/chart-drawings API surface pin', () => {
  it('exports exactly the pinned names', () => {
    expect(Object.keys(api).sort()).toEqual(Object.keys(SURFACE).sort())
  })

  it('every export keeps its pinned runtime type', () => {
    for (const [name, kind] of Object.entries(SURFACE)) {
      expect(typeof (api as Record<string, unknown>)[name], name).toBe(kind)
    }
  })

  // The registry restore contract (every tool constructs + round-trips) is already pinned by
  // serialization.test.ts — the pin here stays name/kind-level on purpose.
})
