// The seam's own surface inventory. This is an INTERNAL source module bundled into quickcharts, so
// a diff here is not a SemVer event: it is an accident check. Each of the 90 tools has a class the
// registry builds drawings from, and dropping one silently would take a tool off the chart, so
// every export is named and a loss fails loudly here.
//
// The PUBLIC contract is quickcharts/drawings, pinned in test/drawings-surface.test.ts,
// and it publishes a deliberate subset of what is listed below.
import { describe, expect, it } from 'vitest'
import * as api from '../../../src/internal/drawings/index'

const SURFACE: Record<string, string> = {
  AbcdPattern: 'function',
  BAR_PRICE_SOURCES: 'object',
  BARS_PATTERN_MODES: 'object',
  POSITION_STATS: 'object',
  QTY_PRECISIONS: 'object',
  AnchoredVolumeProfile: 'function',
  AnchoredVwap: 'function',
  Arc: 'function',
  Arrow: 'function',
  ArrowMarkDown: 'function',
  ArrowMarkUp: 'function',
  ArrowMarker: 'function',
  BarsPattern: 'function',
  Brush: 'function',
  Callout: 'function',
  CapturedBarsDrawing: 'function',
  Circle: 'function',
  Comment: 'function',
  ContentCard: 'function',
  CrossLine: 'function',
  Curve: 'function',
  CyclicLines: 'function',
  CypherPattern: 'function',
  DEFAULT_OPTIONS: 'object',
  DEFAULT_STYLE: 'object',
  DEFAULT_VISIBILITY: 'object',
  DatePriceRange: 'function',
  DateRange: 'function',
  DisjointChannel: 'function',
  DoubleCurve: 'function',
  Drawing: 'function',
  DrawingManager: 'function',
  ELLIOTT_DEGREES: 'object',
  ElliottCorrection: 'function',
  ElliottDoubleCombo: 'function',
  ElliottImpulse: 'function',
  ElliottTriangle: 'function',
  ElliottTripleCombo: 'function',
  Ellipse: 'function',
  ExtendedLine: 'function',
  FibArcs: 'function',
  FibChannel: 'function',
  FibCircles: 'function',
  FibExtension: 'function',
  FibRetracement: 'function',
  FibSpeedFan: 'function',
  FibSpiral: 'function',
  FibTimeExtension: 'function',
  FibTimeZone: 'function',
  FibWedge: 'function',
  FixedRangeVolumeProfile: 'function',
  FlagMark: 'function',
  FlatTopBottom: 'function',
  Forecast: 'function',
  GannBox: 'function',
  GannSquareBase: 'function',
  GannFan: 'function',
  GannSquare: 'function',
  GannSquareFixed: 'function',
  GhostFeed: 'function',
  GlyphMark: 'function',
  HeadAndShoulders: 'function',
  Highlighter: 'function',
  HorizontalLine: 'function',
  HorizontalRay: 'function',
  IconMark: 'function',
  ImageNote: 'function',
  InfoLine: 'function',
  InsidePitchfork: 'function',
  LabeledPolyline: 'function',
  LongPosition: 'function',
  MIXED_LEVEL_COLORS: 'object',
  Measure: 'function',
  ModifiedSchiffPitchfork: 'function',
  Note: 'function',
  ParallelChannel: 'function',
  PathLine: 'function',
  Pin: 'function',
  Pitchfan: 'function',
  Pitchfork: 'function',
  Polyline: 'function',
  PriceLabel: 'function',
  PriceNote: 'function',
  PriceRange: 'function',
  Ray: 'function',
  Rectangle: 'function',
  RegressionTrend: 'function',
  RotatedRectangle: 'function',
  SchiffPitchfork: 'function',
  Sector: 'function',
  ShortPosition: 'function',
  Signpost: 'function',
  SineLine: 'function',
  StickerMark: 'function',
  TOOL_CATEGORIES: 'object',
  TableNote: 'function',
  TextLabel: 'function',
  ThreeDrivesPattern: 'function',
  TimeCycles: 'function',
  ToolRegistry: 'function',
  TrendAngle: 'function',
  TrendLine: 'function',
  Triangle: 'function',
  TrianglePattern: 'function',
  VerticalLine: 'function',
  XabcdPattern: 'function',
  alphaOf: 'function',
  angleOf: 'function',
  barsInRange: 'function',
  cachedImageBitmap: 'function',
  distanceToLine: 'function',
  distanceToSegment: 'function',
  extendSegment: 'function',
  elliottLabel: 'function',
  fanRatioText: 'function',
  fibLevelColor: 'function',
  linearRegression: 'function',
  magnetSnap: 'function',
  midpoint: 'function',
  normalizeVisibility: 'function',
  parseDrawingsStore: 'function',
  parseTimeframeContext: 'function',
  primeImageBitmap: 'function',
  restoreDrawings: 'function',
  segmentTextAngle: 'function',
  serializeDrawingsStore: 'function',
  gannRatioText: 'function',
  sharedLevelColor: 'function',
  snapToBar: 'function',
  toolRegistry: 'object',
  viewportOf: 'function',
  // The quick per-timeframe visibility rules.
  visibilityPreset: 'function',
  visibleAt: 'function',
  volumeProfile: 'function',
  withAlpha: 'function',
}

describe('internal drawing module API surface pin', () => {
  it('exports exactly the pinned names', () => {
    expect(Object.keys(api).sort()).toEqual(Object.keys(SURFACE).sort())
  })

  it('every export keeps its pinned runtime type', () => {
    for (const [name, kind] of Object.entries(SURFACE)) {
      expect(typeof (api as Record<string, unknown>)[name], name).toBe(kind)
    }
  })

  // The registry restore contract (every tool constructs + round-trips) is already pinned by
  // serialization.test.ts — the pin here stays name/kind-level on purpose.
})
