// @vitest-environment happy-dom
// The feature manifest against the source: a public feature manifest generated from the same registries
// the chart uses, so configuration docs, the API reference, examples and product claims can be checked
// against it. scripts/build-feature-manifest.mjs writes dist/feature-manifest.json from the built
// entrypoints; this fixture reads it back and holds every block to the registries the inventory tests pin,
// so the published inventory and the source cannot disagree. The blocks over the built file are vacuous
// until a build has run, the shape the other dist fixtures use: `pnpm --filter quickcharts build`.
import { describe, expect, it } from 'vitest'
import manifest from '../../package.json'
import { BUILT_IN_LOCALES, valueShaped, type ChartStyleId } from '../../src/index'
import { resolveFeatures } from '../../src/widget/planes'
import { THEME_MODES, THEME_ROLES } from '../../src/theme/schema'
import { fakeWidget } from '../chrome/harness'
import { builtArtifact } from '../theme/stylesheetSource'
import fixture from './ids.fixture.json'

interface FeatureManifest {
  version: string
  styles: { id: string; valueShaped: boolean }[]
  indicators: { id: string; tag: string; category: string; pane: string }[]
  drawings: { id: string; category: string; anchors: number; placement?: string }[]
  layouts: { id: string; panes: number }[]
  timeframes: { id: string; unit: string }[]
  timezones: { id: string; city: string }[]
  commands: { id: string; scope: string; shortcut?: string }[]
  features: { id: string; default: boolean }[]
  themes: { modes: string[]; roles: { id: string; family: string; kind: string }[] }
  locales: { id: string; tag: string; dir: string }[]
}

const text = builtArtifact('feature-manifest.json')
const built: FeatureManifest | null = text === null ? null : (JSON.parse(text) as FeatureManifest)

const ids = (rows: readonly { id: string }[]): string[] => rows.map((r) => r.id).sort()

describe('the feature manifest is generated by the build', () => {
  it('runs after the theme generator on every build, and can be run alone', () => {
    expect(manifest.scripts['build:manifest']).toBe('node scripts/build-feature-manifest.mjs')
    expect(manifest.scripts.postbuild.startsWith('node scripts/build-theme.mjs && node scripts/build-feature-manifest.mjs')).toBe(true)
  })

  it('is packed beside the bundle, the way the theme manifest is', () => {
    expect(manifest.files).toContain('dist')
  })
})

describe('the built manifest against the source registries', () => {
  it('publishes exactly the ten blocks, under the package version', () => {
    if (!built) return
    expect(Object.keys(built).sort()).toEqual(['commands', 'drawings', 'features', 'indicators', 'layouts', 'locales', 'styles', 'themes', 'timeframes', 'timezones', 'version'])
    expect(built.version).toBe(manifest.version)
  })

  for (const registry of ['styles', 'indicators', 'drawings', 'layouts', 'timeframes', 'timezones'] as const) {
    it(`${registry}: the same ids the inventory pins, every one once`, () => {
      if (!built) return
      expect(ids(built[registry])).toEqual(fixture.registries[registry])
    })
  }

  it('styles carry the value-shaped predicate the legend and replay branch on', () => {
    if (!built) return
    for (const row of built.styles) expect(row.valueShaped, row.id).toBe(valueShaped(row.id as ChartStyleId))
  })

  it('commands: every verb the widget registers, with its scope and default shortcut', () => {
    if (!built) return
    expect(ids(built.commands)).toEqual(fixture.registries.commands)
    const w = fakeWidget()
    try {
      const registered = new Map(w.commands.list().map((s) => [s.id, s]))
      for (const row of built.commands) {
        const spec = registered.get(row.id)
        expect(spec, row.id).toBeDefined()
        expect(row.scope, row.id).toBe(spec!.scope)
        expect(row.shortcut, row.id).toBe(spec!.shortcut)
      }
    } finally {
      w.dispose()
    }
  })

  it('features: every flag of the feature plane, each on by default', () => {
    if (!built) return
    const resolved = resolveFeatures()
    expect(ids(built.features)).toEqual(Object.keys(resolved).sort())
    for (const row of built.features) expect(row.default, row.id).toBe(true)
  })

  it('themes: both built-in modes over the whole role inventory', () => {
    if (!built) return
    expect(built.themes.modes).toEqual([...THEME_MODES])
    expect(ids(built.themes.roles)).toEqual(fixture.registries.themeRoles)
    const byId = new Map<string, { family: string; kind: string }>(THEME_ROLES.map((r) => [r.id, r]))
    for (const row of built.themes.roles) {
      expect(row.family, row.id).toBe(byId.get(row.id)!.family)
      expect(row.kind, row.id).toBe(byId.get(row.id)!.kind)
    }
  })

  it('locales: the built-in inventory with its tags and reading directions', () => {
    if (!built) return
    expect(ids(built.locales)).toEqual(fixture.registries.locales)
    const byCode = new Map(BUILT_IN_LOCALES.map((l) => [l.code, l]))
    for (const row of built.locales) {
      expect(row.tag, row.id).toBe(byCode.get(row.id as never)!.tag)
      expect(row.dir, row.id).toBe(byCode.get(row.id as never)!.dir)
    }
  })
})
